package aula;

import viewcadastro.*;
import controller.ControllerUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Usuario;
import principal.BCrypt;
import principal.Conexao;
import viewconsulta.consultaUsuarios;

/**
 * @author Gelvazio Camargo
 */
public class CadastroUsuario extends javax.swing.JFrame {
    Usuario usuario = new Usuario();
    ControllerUsuario controller = new ControllerUsuario();
    consultaUsuarios consulta = new consultaUsuarios(this, true);
    boolean existeUsuario = false;
    
    public CadastroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        edtCodigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        btnAlterarSenha = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        edtLogin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGravar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        edtSenha3 = new javax.swing.JPasswordField();
        edtSenha2 = new javax.swing.JPasswordField();
        edtSenha1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Usuários");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 470, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Senha Atual");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Código");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nome");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Login");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, -1));

        edtNome.setEnabled(false);
        edtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtNomeKeyPressed(evt);
            }
        });
        getContentPane().add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 410, -1));

        edtEmail.setEnabled(false);
        getContentPane().add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 410, -1));

        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Valid Green.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.setEnabled(false);
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 180, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Remove Red.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.setEnabled(false);
        jButton3.setPreferredSize(new java.awt.Dimension(101, 41));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 130, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Cancel.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.setEnabled(false);
        jButton4.setPreferredSize(new java.awt.Dimension(101, 41));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 130, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 610, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 610, 10));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 610, 10));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Search.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 40, 40));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Add.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Red.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 130, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("E-mail");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        edtLogin.setEnabled(false);
        getContentPane().add(edtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 410, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("E-mail");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Confirmar Senha");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Valid Green.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Senha");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        edtSenha3.setBackground(new java.awt.Color(242, 242, 242));
        edtSenha3.setEnabled(false);
        getContentPane().add(edtSenha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 180, -1));

        edtSenha2.setBackground(new java.awt.Color(242, 242, 242));
        edtSenha2.setEnabled(false);
        getContentPane().add(edtSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        edtSenha1.setBackground(new java.awt.Color(242, 242, 242));
        edtSenha1.setEnabled(false);
        getContentPane().add(edtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 200, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Knob Cancel.png"))); // NOI18N
        jButton2.setText("GELVAZIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        executaAlteracaoSenha();
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (controller.excluirRegistro(Integer.parseInt(edtCodigo.getText()))) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            limpaCampos();
            habilitaCampos(false);
            edtCodigo.requestFocus();
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_TAB)) {
            if (edtCodigo.getText().equals("")) {
                edtCodigo.setText(String.valueOf(Conexao.getProximoCodigo("usuario", usuario)));
                habilitaCampos(true);
                edtNome.requestFocus();
                edtSenha3.setEnabled(false);
                btnAlterarSenha.setEnabled(false);
            } else {
                int codigo = Integer.parseInt(edtCodigo.getText());                
                if (controller.existeRegistro(codigo)) {
                    existeUsuario = true;
                    usuario = controller.getRegistro(codigo);
                    edtNome.setText(usuario.getNome());
                    edtEmail.setText(usuario.getEmail());
                    edtLogin.setText(usuario.getLogin());

                    habilitaCampos(true);
                    edtNome.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Registro não existe!");
                    habilitaCampos(false);
                    edtCodigo.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            edtEmail.requestFocus();
        }
    }//GEN-LAST:event_edtNomeKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpaCampos();
        habilitaCampos(false);
        edtCodigo.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        edtCodigo.setText(String.valueOf(Conexao.getProximoCodigo("usuario", usuario)));                
        habilitaCampos(true);
        edtNome.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        consulta.setVisible(true);
        edtCodigo.setText(String.valueOf(consulta.codigo));
        edtCodigo.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        executaInclusaoAlteracao();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JOptionPane.showMessageDialog(null, "Ola");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    public void habilitaCampos(boolean habilita) {
        edtNome.setEnabled(habilita);
        edtEmail.setEnabled(habilita);
        edtLogin.setEnabled(habilita);
        
        edtSenha1.setEnabled(habilita);
        edtSenha2.setEnabled(habilita);
        edtSenha3.setEnabled(habilita);            
        
        btnAlterarSenha.setEnabled(habilita);
        btnGravar.setEnabled(habilita);
        jButton3.setEnabled(habilita);
        jButton4.setEnabled(habilita);

        edtCodigo.setEnabled(!habilita);
        jButton5.setEnabled(!habilita);
        jButton6.setEnabled(!habilita);
        jButton1.setEnabled(!habilita);
    }

    public void limpaCampos() {
        edtCodigo.setText("");
        edtNome.setText("");
        edtEmail.setText("");
        edtLogin.setText("");
        edtSenha1.setText("");
        edtSenha2.setText("");        
        edtSenha3.setText("");        
    }
    
    private void executaInclusaoAlteracao() {
        int codigo = Integer.parseInt(edtCodigo.getText());
        usuario.setCodigo(codigo);
        usuario.setEmail(edtEmail.getText());
        usuario.setLogin(edtLogin.getText());
        usuario.setNome(edtNome.getText());
        
        String senha1 = new String(edtSenha1.getPassword());
        String senha2 = new String(edtSenha2.getPassword());
        
        // Valida se as senhas são iguais
        if(senha1.equals(senha2)){
            boolean executou;
            if(controller.existeRegistro(codigo)){
                executou = controller.gravarAlteracao(usuario);
            } else {
                // Somente grava a senha na inclusão, tem um btão pra alterar senha depois...
                usuario.setSenha(senha1);
                executou = controller.gravarInclusao(usuario);                
            }
            
            if(executou){
                JOptionPane.showMessageDialog(null, "Registro gravado/alterado com sucesso!");
                limpaCampos();
                habilitaCampos(false);
                edtCodigo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao gravar/alterar registro!");                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha não confere!");
        }    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnGravar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtLogin;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha1;
    private javax.swing.JPasswordField edtSenha2;
    private javax.swing.JPasswordField edtSenha3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables

    private boolean executaAlteracaoSenha() {
        
        String senha1 = new String(edtSenha1.getPassword());
        String senha2 = new String(edtSenha2.getPassword());
        String senha3 = new String(edtSenha3.getPassword());
        
        if(senha1.equals("") || senha2.equals("") || senha3.equals("")){
            JOptionPane.showMessageDialog(null, "Informe a senha atual, nova senha e confirmação de senha!!");
            return false;
        }
        
        if(!existeUsuario){
            JOptionPane.showMessageDialog(null, "Grave o usuário primeiro!");
            return false;
        }
        
        int codigo = Integer.parseInt(edtCodigo.getText());
        
        // Antes de iniciar a alteração, verifica se login e senha atual confere
        String login = edtLogin.getText();
        String senhaAtual = edtSenha3.getText();
        if (!controller.validaLoginSenha(login, senhaAtual)) {
            JOptionPane.showMessageDialog(null, "Login/Senha atual não confere!");
            return false;
        }
        
        // Valida se as 2 novas senhas são iguais
        if(senha1.equals(senha2)){
            boolean executou = false;
            if(controller.existeRegistro(codigo)){
                String senhaEncriptada = BCrypt.hashpw(senha1, BCrypt.gensalt());
                String update = "UPDATE USUARIO SET ususenha = '" + senhaEncriptada + "' WHERE USUCODIGO = " + codigo;
                executou = Conexao.executeUpdate(update);
            }
            
            if(executou){
                JOptionPane.showMessageDialog(null, "Senha alterada com sucesso!");
                limpaCampos();
                habilitaCampos(false);                
                edtCodigo.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao alterar senha!");                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senha e Confirmação de senha não conferem!");
        }
        
        return true;
    }
}
