package aula;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class consultaProdutosNovo extends javax.swing.JFrame {

    /**
     * Creates new form consultaProdutos
     */
    public consultaProdutosNovo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        comboboxFiltro = new javax.swing.JComboBox<>();
        edtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboboxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(comboboxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(comboboxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(434, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("clicou em consultar!!");
        if (edtPesquisa.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Informe um valor para pesquisa!");
        } else {
            int selecionado = comboboxFiltro.getSelectedIndex();
            System.out.println("selecionado:" + selecionado);

            try {
                ArrayList<Produto> listaProdutos = getAllProdutos(selecionado);
                int totalRegistros = listaProdutos.size();
                if (totalRegistros == 0) {
                    JOptionPane.showMessageDialog(null, "Produto não encontrado para filtro selecionado!");
                }
            } catch (IOException ex) {
                Logger.getLogger(consultaProdutosNovo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // lista produtos
    public ArrayList<Produto> getAllProdutos(int selecionado) throws IOException {
        String sql = "";

        // CODIGO SELECIONADO
        if (selecionado == 0) {
            int codigo = Integer.parseInt(edtPesquisa.getText());
            sql = "select * from produto WHERE id = " + codigo + " order by id";
        } else if (selecionado == 1) {
            String descricao = edtPesquisa.getText();
            sql = "select * from produto WHERE descricao ilike '%" + descricao + "%' order by id";
        }

        Produto produto = new Produto();
        ArrayList<Produto> listaProdutos = Conexao.executaQuery(sql, produto);
        for (Produto auxProduto : listaProdutos) {
            System.out.println("Codigo:" + auxProduto.getId());

            System.out.println("Descricao:" + auxProduto.getDescricao());
            System.out.println("Preco Custo:" + auxProduto.getPrecocusto());
            System.out.println("Preco Venda:" + auxProduto.getPrecovenda());
            System.out.println("-----------------------------");
        }
        return listaProdutos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultaProdutosNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultaProdutosNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultaProdutosNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultaProdutosNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultaProdutosNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxFiltro;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
